name: shape_template CI
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Run Makefile (make all)
        run: |
          make all

      - name: Docker build/test
        run: |
          set -e  # exit immediately on error
          docker build . --file Dockerfile --tag ci_workflow > ./build/docker.log 2>&1
          docker run --rm ci_workflow circle 10
          docker run --rm ci_workflow cube 10 scale 4
      
      - name: Upload log file on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: ./build/log-file.log
