name: shape_template CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: |
          mkdir -p build
          { ./run_shapes.sh > ./build/run.log 2>&1 || { echo "Script failed" && exit 1; }; }
          cat ./build/run.log

      - name: Upload run log file
        uses: actions/upload-artifact@v4
        with:
          name: run-log-file
          path: build/run.log

      - name: Upload log file on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: script-log-file
          path: ./build/f_script.log

  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Run Makefile (make all)
        run: make all

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Docker build/test
        run: |
          mkdir -p build
          { ./run_shapes.sh Docker > ./build/docker.log 2>&1 || { echo "Script failed" && exit 1; }; }
          cat ./build/docker.log

      - name: Upload log file on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-log-file
          path: ./build/f_docker.log
