name: CI
on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: |
          { ./run_shapes.sh > ./build/run.log 2>&1 || { echo "Script failed" && exit 1; }; }  
          cat ./build/run.log
      - name: upload-run-log-file
        uses: actions/upload-artifact@v4
        with:
          name: run-log-file
          path: build/run.log
      - name: Upload log file on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: script-log-file
          path: ./build/f_script.log

  docker:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v4
        - name: Build Docker image
          run: |
            { docker build . --file Dockerfile --tag image:ci_workflow || { echo "Failed to create image" && exit 1; }; }
        - name: Run Docker container
          run: |
            { docker run --rm image:ci_workflow || { echo "Failed to run image" && exit 1; }; }
        - name: Upload log file on failure
          if: failure()
          uses: actions/upload-artifact@v4 
          with:
            name: docker-log-file
            path: ./build/f_docker.log
        
